version: "3.9"

services:
  api:
    container_name: ${DOCKER_SERVICE_NAME}
    build: .
    env_file:
      - .env
    ports:
      - ${DOCKER_SERVICE_PORT}:8000
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
  
  db:
    image: mysql:8.0  
    container_name: ${DOCKER_MYSQL_NAME}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 1s
      retries: 30
    ports:
      - ${DOCKER_MYSQL_PORT}:3306
    networks:
      - backend

networks:
  backend:
    name: ${DOCKER_NETWORK}